name: Const

on:
  push:
    branches:
      - master
    paths:
      - 'packages/const/**'

  pull_request:
    paths:
      - 'packages/const/**'

  workflow_dispatch: {}

defaults:
  run:
    working-directory: ./packages/const

jobs:
  const:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8.6.2
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
      - run: pnpm check:type
      - run: pnpm test
      - name: Publish
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        uses: mlchain/gh-actions/publish-if-not-exists@master
        with:
          path: './const'
          token: '${{ secrets.NPM_ACCESS_TOKEN }}'
